name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
      name: Checkout Nzyme
      with:
        repository: nzymedefense/nzyme
    - name: Install libpcap
      run: sudo apt install libpcap0.8 libpcap0.8-dev
    - name: Build
      run: |
        ls -ahltr
        cd tap 
        cargo build --verbose -r
    - name: Run tests
      run: |
        cd tap
        cargo test --verbose
    - name: Upload nzyme-tap
      uses: actions/upload-artifact@v4
      with:
        name: nzyme-tap
        path: tap/target/release/nzyme-tap
