name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-20.04
    name: Build on ${{ matrix.distro }} ${{ matrix.arch }}
    # Run steps on a matrix of 4 arch/distro combinations
    strategy:
      matrix:
        include:
          #- arch: aarch64
          #  distro: ubuntu20.04
          #- arch: aarch64
          #  distro: ubuntu22.04 
          - arch: armv7
            distro: ubuntu20.04
          #- arch: armv7
          #  distro: ubuntu22.04
    steps:
    - uses: actions/checkout@v3
      name: Checkout Nzyme
      with:
        repository: nzymedefense/nzyme
    
    - uses: uraimo/run-on-arch-action@v2
      name: Run commands
      id: runcmd
      with:
        arch: ${{ matrix.arch }}
        distro: ${{ matrix.distro }}
        dockerRunArgs: |
          --volume "${PWD}:/nzyme"
        install: |
          apt-get update -q -y
          apt-get install -y libpcap0.8 cargo openssl librust-openssl-dev
        run: |
          pwd
          ls -ahltr
          cd /nzyme/tap
          cargo build --verbose -r
    - name: Upload nzyme-tap
      uses: actions/upload-artifact@v4
      with:
        name: nzyme-tap-${{ matrix.arch }}-${{ matrix.distro }}
        path: tap/target/release/nzyme-tap
