name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-20.04
    name: Build on ${{ matrix.debian-port }} ${{ matrix.distro }}
    # Run steps on a matrix of 4 arch/distro combinations
    strategy:
      matrix:
        include:
          # Debian port name: https://www.debian.org/ports/arm/
          - arch: aarch64
            debian-port: arm64
            distro: ubuntu20.04
            codename: focal
          - arch: aarch64
            debian-port: arm64
            distro: ubuntu22.04 
            codename: jammy
          - arch: armv7
            debian-port: armhf
            distro: ubuntu20.04
            codename: focal
          - arch: armv7
            debian-port: armhf
            distro: ubuntu22.04
            codename: jammy
    steps:
    - uses: actions/checkout@v4
      name: Checkout Nzyme
      with:
        repository: iagotomas/nzyme
    - uses: uraimo/run-on-arch-action@v2
      name: Run commands
      id: runcmd
      with:
        arch: ${{ matrix.arch }}
        distro: ${{ matrix.distro }}
        # Not required, but speeds up builds by storing container images in
        # a GitHub package registry.
        githubToken: ${{ github.token }}
        dockerRunArgs: |
          --volume "${PWD}:/nzyme"
        install: |
          case "${{ matrix.distro }}" in
            ubuntu*)
              echo "deb-src http://ports.ubuntu.com/ubuntu-ports ${{matrix.codename}} main" > /etc/apt/sources.list.d/debian-src.list
              apt-get update -q -y
              apt-get install -y dpkg-dev build-essential cargo openssl librust-openssl-dev libnl-genl-3-dev dh-autoreconf flex libbluetooth-dev autotools-dev bison debhelper
              mkdir -p source/libpcap/source
              cd source/libpcap/source
              apt-get source -y libpcap0.8
              read -r version build < <(grep -E "^Version.*" *.dsc|awk '{print $2}'|awk -F'-' '{print $1, $2}')
              cd libpcap-${version}
              export with_libnl=yes
              apt build-dep .
              dpkg-buildpackage -uc -us -b
              cd ..
              dpkg -i libpcap0.8_${version}-${build}_${{ matrix.debian-port }}.deb
              dpkg -i libpcap0.8-dev_${version}-${build}_${{ matrix.debian-port }}.deb
              ;;
          esac
        run: |
          cd /nzyme/tap
          cargo build --verbose -r
    - name: Upload nzyme-tap ${{ matrix.distro }} ${{ matrix.debian-port }} 
      uses: actions/upload-artifact@v4
      with:
        name: nzyme-tap-${{ matrix.distro }}-${{ matrix.debian-port }}
        path: tap/target/release/nzyme-tap
