name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
      name: Checkout Nzyme
      with:
        repository: nzymedefense/nzyme
    
    - uses: uraimo/run-on-arch-action@v2
      name: Run commands
      id: runcmd
      with:
        arch: armv7
        distro: ubuntu22.04
        dockerRunArgs: |
          --volume "${PWD}:/nzyme"
        install: |
          apt-get update -q -y
          apt-get install -y libpcap0.8
        run: |
          pwd
          ls -ahltr
          cd /nzyme/tap
          cargo build --verbose -r
    - name: Upload nzyme-tap
      uses: actions/upload-artifact@v4
      with:
        name: nzyme-tap
        path: tap/target/release/nzyme-tap
